services:
  api1:
    build:
      context: ./api
      platforms:
        - linux/amd64
    container_name: rinha-nginx-api1
    environment:
      - MODE=api
      - SOCKET_PATH=/sockets/api1.sock
    volumes:
      - rinha_nginx_sockets:/sockets
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "140MB"

  api2:
    build:
      context: ./api
      platforms:
        - linux/amd64
    container_name: rinha-nginx-api2
    environment:
      - MODE=api
      - SOCKET_PATH=/sockets/api2.sock
    volumes:
      - rinha_nginx_sockets:/sockets
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "140MB"

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: rinha-nginx-lb
    ports:
      - "19998:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - rinha_nginx_sockets:/sockets:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"

volumes:
  rinha_nginx_sockets:
