version: "3.8"

services:
  api1:
    image: ghcr.io/bentoplebstguida/rinha-fraud-api:latest
    container_name: api1
    platform: linux/amd64
    environment:
      - INDEX_PATH=/app/data/index.faiss
      - LABELS_PATH=/app/data/labels.npy
      - MCC_PATH=/app/data/mcc_risk.json
      - NORM_PATH=/app/data/normalization.json
      - NPROBE=32
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "140MB"
    networks:
      - fraud-net

  api2:
    image: ghcr.io/bentoplebstguida/rinha-fraud-api:latest
    container_name: api2
    platform: linux/amd64
    environment:
      - INDEX_PATH=/app/data/index.faiss
      - LABELS_PATH=/app/data/labels.npy
      - MCC_PATH=/app/data/mcc_risk.json
      - NORM_PATH=/app/data/normalization.json
      - NPROBE=32
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "140MB"
    networks:
      - fraud-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"
    networks:
      - fraud-net
    depends_on:
      - api1
      - api2

networks:
  fraud-net:
    driver: bridge
